#!/bin/bash
# Guide to switch to correct AWS account

set -e

echo "=========================================="
echo "Switch to Correct AWS Account"
echo "=========================================="
echo ""
echo "Current account: 248894199474 (WRONG)"
echo "Needed account: 640768199126 (CORRECT)"
echo ""
echo "You need to configure AWS CLI with credentials from account 640768199126"
echo ""

# Check current config
echo "Current AWS configuration:"
echo "---------------------------"
if [ -f ~/.aws/credentials ]; then
    echo "Credentials file exists: ~/.aws/credentials"
    echo ""
    echo "Current profiles:"
    grep -E "^\[.*\]" ~/.aws/credentials 2>/dev/null || echo "  (no profiles found)"
else
    echo "No credentials file found"
fi
echo ""

# Check config file
if [ -f ~/.aws/config ]; then
    echo "Config file exists: ~/.aws/config"
    echo ""
    echo "Current profiles:"
    grep -E "^\[profile.*\]|^\[default\]" ~/.aws/config 2>/dev/null || echo "  (no profiles found)"
else
    echo "No config file found"
fi
echo ""

echo "=========================================="
echo "How to Fix"
echo "=========================================="
echo ""
echo "Option 1: Configure new profile (Recommended)"
echo "---------------------------------------------"
echo "Run this command and enter credentials for account 640768199126:"
echo ""
echo "  aws configure --profile health-data"
echo ""
echo "You'll need:"
echo "  - AWS Access Key ID (from account 640768199126)"
echo "  - AWS Secret Access Key (from account 640768199126)"
echo "  - Default region: us-east-2"
echo "  - Default output: json"
echo ""
echo "Then use it:"
echo "  export AWS_PROFILE=health-data"
echo ""
echo "Option 2: Update default credentials"
echo "-------------------------------------"
echo "If you want to replace your default credentials:"
echo ""
echo "  aws configure"
echo ""
echo "Enter credentials for account 640768199126"
echo ""
echo "Option 3: Use environment variables"
echo "------------------------------------"
echo "Set these environment variables:"
echo ""
echo "  export AWS_ACCESS_KEY_ID='your-key-from-640768199126'"
echo "  export AWS_SECRET_ACCESS_KEY='your-secret-from-640768199126'"
echo "  export AWS_DEFAULT_REGION='us-east-2'"
echo ""
echo "=========================================="
echo "After Switching"
echo "=========================================="
echo ""
echo "1. Verify the account:"
echo "   aws sts get-caller-identity"
echo ""
echo "   Should show: Account: 640768199126"
echo ""
echo "2. Test S3 access:"
echo "   aws s3 ls s3://health-data-lake-640768199126-us-east-2/health-data/raw/"
echo ""
echo "3. Test Athena:"
echo "   ./try_without_execution_role.sh"
echo ""
echo "=========================================="
echo "Where to Get Credentials"
echo "=========================================="
echo ""
echo "If you have access to AWS Console for account 640768199126:"
echo "1. Go to: IAM → Users → (your user)"
echo "2. Security credentials tab"
echo "3. Create access key"
echo ""
echo "Or if you have access keys already, use those."
echo ""

